spring:
  application:
    name: glass-per-hour

server:
  port: 8000

# Logging Configuration
logging:
  charset:
    console: UTF-8

# Gemini API Configuration
gemini:
  api:
    key: AIzaSyD4EaW_NWCeTXKaxVYkBBUipRHitRYSmG0
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Reaction Game Scheduler
scheduler:
  reaction-game:
    interval-hours: 1
    enabled: true
